// Code generated by goctl. DO NOT EDIT.
package types

type AddVerifyRequest struct {
	VerifyType string   `json:"verify_type"`
	VerifyInfo []string `json:"verify_info"`
	JobTiele   string   `json:"job_tiele"`
	IsPay      int64    `json:"is_pay"`
	Creator    string   `json:"creator"`
}

type AddVerifyResponse struct {
	Repetition []string `json:"repetition"`
}
