// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	reportRecordFieldNames          = builder.RawFieldNames(&ReportRecord{})
	reportRecordRows                = strings.Join(reportRecordFieldNames, ",")
	reportRecordRowsExpectAutoSet   = strings.Join(stringx.Remove(reportRecordFieldNames, "`id`", "`create_time`", "`update_time`"), ",")
	reportRecordRowsWithPlaceHolder = strings.Join(stringx.Remove(reportRecordFieldNames, "`id`", "`create_time`", "`update_time`"), "=?,") + "=?"
)

type (
	reportRecordModel interface {
		Insert(ctx context.Context, data *ReportRecord) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*ReportRecord, error)
		Update(ctx context.Context, data *ReportRecord) error
		Delete(ctx context.Context, id int64) error
	}

	defaultReportRecordModel struct {
		conn  sqlx.SqlConn
		table string
	}

	ReportRecord struct {
		Id         int64          `db:"id"`
		VerifyInfo string         `db:"verify_info"` // 验证信息
		VerifyType string         `db:"verify_type"` // 验证类型
		SocialName sql.NullString `db:"social_name"` // 名称
		JobTiele   sql.NullString `db:"job_tiele"`   // 职位
		Creator    sql.NullString `db:"creator"`     // 创建人
		IsPay      sql.NullString `db:"is_pay"`      // 是否接受付款
		CreateTime time.Time      `db:"create_time"` // 创建时间
		UpdateTime time.Time      `db:"update_time"` // 修改时间
		IsDelete   int64          `db:"is_delete"`   // 删除标识 0 未删除 1 已删除
		Ctime      time.Time      `db:"ctime"`       // 创建时间
		Mtime      time.Time      `db:"mtime"`       // 修改时间
	}
)

func newReportRecordModel(conn sqlx.SqlConn) *defaultReportRecordModel {
	return &defaultReportRecordModel{
		conn:  conn,
		table: "`report_record`",
	}
}

func (m *defaultReportRecordModel) Insert(ctx context.Context, data *ReportRecord) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, reportRecordRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.VerifyInfo, data.VerifyType, data.SocialName, data.JobTiele, data.Creator, data.IsPay, data.IsDelete, data.Ctime, data.Mtime)
	return ret, err
}

func (m *defaultReportRecordModel) FindOne(ctx context.Context, id int64) (*ReportRecord, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", reportRecordRows, m.table)
	var resp ReportRecord
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultReportRecordModel) Update(ctx context.Context, data *ReportRecord) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, reportRecordRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.VerifyInfo, data.VerifyType, data.SocialName, data.JobTiele, data.Creator, data.IsPay, data.IsDelete, data.Ctime, data.Mtime, data.Id)
	return err
}

func (m *defaultReportRecordModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultReportRecordModel) tableName() string {
	return m.table
}
