// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	verifyEnumFieldNames          = builder.RawFieldNames(&VerifyEnum{})
	verifyEnumRows                = strings.Join(verifyEnumFieldNames, ",")
	verifyEnumRowsExpectAutoSet   = strings.Join(stringx.Remove(verifyEnumFieldNames, "`id`", "`create_time`", "`update_time`"), ",")
	verifyEnumRowsWithPlaceHolder = strings.Join(stringx.Remove(verifyEnumFieldNames, "`id`", "`create_time`", "`update_time`"), "=?,") + "=?"
)

type (
	verifyEnumModel interface {
		Insert(ctx context.Context, data *VerifyEnum) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*VerifyEnum, error)
		Update(ctx context.Context, data *VerifyEnum) error
		Delete(ctx context.Context, id int64) error
	}

	defaultVerifyEnumModel struct {
		conn  sqlx.SqlConn
		table string
	}

	VerifyEnum struct {
		Id         int64     `db:"id"`
		VerifyType string    `db:"verify_type"` // 验证类型
		CreateTime time.Time `db:"create_time"` // 创建时间
		UpdateTime time.Time `db:"update_time"` // 修改时间
		IsDelete   int64     `db:"is_delete"`   // 删除标识 0 未删除 1 已删除
		Ctime      time.Time `db:"ctime"`       // 创建时间
		Mtime      time.Time `db:"mtime"`       // 修改时间
	}
)

func newVerifyEnumModel(conn sqlx.SqlConn) *defaultVerifyEnumModel {
	return &defaultVerifyEnumModel{
		conn:  conn,
		table: "`verify_enum`",
	}
}

func (m *defaultVerifyEnumModel) Insert(ctx context.Context, data *VerifyEnum) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?)", m.table, verifyEnumRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.VerifyType, data.IsDelete, data.Ctime, data.Mtime)
	return ret, err
}

func (m *defaultVerifyEnumModel) FindOne(ctx context.Context, id int64) (*VerifyEnum, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", verifyEnumRows, m.table)
	var resp VerifyEnum
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultVerifyEnumModel) Update(ctx context.Context, data *VerifyEnum) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, verifyEnumRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.VerifyType, data.IsDelete, data.Ctime, data.Mtime, data.Id)
	return err
}

func (m *defaultVerifyEnumModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultVerifyEnumModel) tableName() string {
	return m.table
}
