// Code generated by goctl. DO NOT EDIT!
// Source: verify.proto

package server

import (
	"context"

	"cointiger.com/verification/app/verify/grpc/internal/logic"
	"cointiger.com/verification/app/verify/grpc/internal/svc"
	"cointiger.com/verification/app/verify/grpc/verify"
)

type VerifyServer struct {
	svcCtx *svc.ServiceContext
	verify.UnimplementedVerifyServer
}

func NewVerifyServer(svcCtx *svc.ServiceContext) *VerifyServer {
	return &VerifyServer{
		svcCtx: svcCtx,
	}
}

func (s *VerifyServer) ListInform(ctx context.Context, in *verify.ListInformRequest) (*verify.ListInformResponse, error) {
	l := logic.NewListInformLogic(ctx, s.svcCtx)
	return l.ListInform(in)
}
