// Code generated by goctl. DO NOT EDIT!
// Source: verify.proto

package verify

import (
	"context"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Verify interface {
		ListInform(ctx context.Context, in *ListInformRequest, opts ...grpc.CallOption) (*ListInformResponse, error)
	}

	defaultVerify struct {
		cli zrpc.Client
	}
)

func NewVerify(cli zrpc.Client) Verify {
	return &defaultVerify{
		cli: cli,
	}
}

func (m *defaultVerify) ListInform(ctx context.Context, in *ListInformRequest, opts ...grpc.CallOption) (*ListInformResponse, error) {
	client := NewVerifyClient(m.cli.Conn())
	return client.ListInform(ctx, in, opts...)
}
